# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacature',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('titel', models.CharField(max_length=250)),
                ('omschrijving', models.TextField()),
                ('dateCreated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
