# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField()),
                ('dateCreated', models.DateTimeField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='VacatureContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=250)),
                ('omschrijving', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='vacature',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontoffice.VacatureContent'),
        ),
    ]
