# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, editable=False, null=True)),
                ('titel', models.CharField(max_length=250)),
                ('omschrijving', models.TextField()),
                ('dateCreated', models.DateTimeField(auto_now=True)),
                ('dateUpdated', models.DateTimeField(blank=True, editable=False, null=True)),
                ('datePublished', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
        ),
    ]
